# Generated by Django 2.0.2 on 2018-10-10 10:57

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.TextField(default='', max_length=100)),
                ('email', models.TextField(default=0)),
                ('phone', models.TextField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_exp', models.DateField(default=datetime.datetime(2018, 10, 10, 10, 57, 29, 125084, tzinfo=utc))),
                ('qty', models.IntegerField(default=1)),
                ('prolonged', models.BooleanField()),
                ('company', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clients.company')),
            ],
        ),
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.TextField(default='', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='data',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clients.services'),
        ),
    ]
