# Generated by Django 2.0.2 on 2018-10-10 15:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='prolonged',
        ),
        migrations.AlterField(
            model_name='data',
            name='date_of_exp',
            field=models.DateField(default=datetime.datetime(2018, 10, 10, 15, 23, 14, 558302, tzinfo=utc)),
        ),
    ]
