# Generated by Django 2.0.2 on 2018-10-10 17:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_auto_20181010_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='date_of_exp',
            field=models.DateField(default=datetime.datetime(2018, 10, 10, 17, 51, 12, 2178, tzinfo=utc)),
        ),
    ]
