# Generated by Django 2.0.2 on 2018-10-12 16:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_auto_20181010_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='price',
            field=models.IntegerField(default=240),
        ),
        migrations.AlterField(
            model_name='data',
            name='date_of_exp',
            field=models.DateField(default=datetime.datetime(2018, 10, 12, 16, 49, 13, 405225, tzinfo=utc)),
        ),
    ]
