# Generated by Django 2.0.2 on 2018-10-13 18:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_auto_20181012_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='date_of_exp',
            field=models.DateField(default=datetime.datetime(2018, 10, 13, 18, 43, 8, 414470, tzinfo=utc)),
        ),
    ]
